use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::discover::module_ident;

/// Lints silenced inside generated modules. Generated code is not written to
/// this workspace's standards and must not fail a `-D warnings` build.
pub(crate) const GENERATED_ALLOWS: &str = "clippy::all, clippy::pedantic, clippy::nursery, \
     missing_docs, unreachable_pub, unused_qualifications, rust_2018_idioms";

#[derive(Default)]
struct Node {
    file: Option<PathBuf>,
    children: BTreeMap<String, Node>,
}

/// Rust source that declares one nested module per package and `include!`s
/// each generated file inside it, under `#![allow(...)]`.
///
/// `generated` pairs a package (empty for files without one) with the path
/// of its generated `.rs` file. Paths are written as string literals, so the
/// wrapper works for any output directory, not only `OUT_DIR`.
pub(crate) fn render(generated: &[(String, PathBuf)]) -> String {
    let mut root = Node::default();
    for (package, file) in generated {
        let mut node = &mut root;
        if !package.is_empty() {
            for segment in package.split('.') {
                node = node.children.entry(segment.to_owned()).or_default();
            }
        }
        node.file = Some(file.clone());
    }
    let mut out = String::from(
        "// @generated by sekvent-proto-build. Do not edit.\n\
         // Include with: include!(concat!(env!(\"OUT_DIR\"), \"/<wrapper file>\"));\n",
    );
    render_node(&root, 0, &mut out);
    out
}

fn render_node(node: &Node, depth: usize, out: &mut String) {
    let indent = "    ".repeat(depth);
    if let Some(file) = &node.file {
        if depth == 0 {
            // A crate root cannot take inner attributes from an include, so
            // package-less code gets its own module.
            let _ = writeln!(out, "#[allow({GENERATED_ALLOWS})]\npub mod __root {{");
            let _ = writeln!(out, "    include!({});", literal(file));
            let _ = writeln!(out, "}}\npub use __root::*;");
        } else {
            let _ = writeln!(out, "{indent}include!({});", literal(file));
        }
    }
    for (segment, child) in &node.children {
        let _ = writeln!(out, "{indent}#[allow({GENERATED_ALLOWS})]");
        let _ = writeln!(out, "{indent}pub mod {} {{", module_ident(segment));
        render_node(child, depth + 1, out);
        let _ = writeln!(out, "{indent}}}");
    }
}

fn literal(path: &Path) -> String {
    format!("{:?}", path.to_string_lossy())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn packages_nest_and_carry_the_allows() {
        let rendered = render(&[
            ("billing.v1".to_owned(), PathBuf::from("/out/billing.v1.rs")),
            ("billing".to_owned(), PathBuf::from("/out/billing.rs")),
            (
                "orders.type.v1".to_owned(),
                PathBuf::from("/out/orders.type.v1.rs"),
            ),
        ]);
        let expected = format!(
            "// @generated by sekvent-proto-build. Do not edit.\n\
             // Include with: include!(concat!(env!(\"OUT_DIR\"), \"/<wrapper file>\"));\n\
             #[allow({GENERATED_ALLOWS})]\n\
             pub mod billing {{\n    \
                 include!(\"/out/billing.rs\");\n    \
                 #[allow({GENERATED_ALLOWS})]\n    \
                 pub mod v1 {{\n        \
                     include!(\"/out/billing.v1.rs\");\n    \
                 }}\n\
             }}\n\
             #[allow({GENERATED_ALLOWS})]\n\
             pub mod orders {{\n    \
                 #[allow({GENERATED_ALLOWS})]\n    \
                 pub mod r#type {{\n        \
                     #[allow({GENERATED_ALLOWS})]\n        \
                     pub mod v1 {{\n            \
                         include!(\"/out/orders.type.v1.rs\");\n        \
                     }}\n    \
                 }}\n\
             }}\n"
        );
        assert_eq!(rendered, expected);
    }

    #[test]
    fn package_less_files_get_a_root_module() {
        let rendered = render(&[(String::new(), PathBuf::from("/out/_.rs"))]);
        assert!(
            rendered
                .contains("pub mod __root {\n    include!(\"/out/_.rs\");\n}\npub use __root::*;")
        );
    }

    #[test]
    fn paths_are_escaped_as_string_literals() {
        assert_eq!(
            literal(Path::new("C:\\out\\a\"b.rs")),
            "\"C:\\\\out\\\\a\\\"b.rs\""
        );
    }

    #[test]
    fn the_allows_cover_the_workspace_lints() {
        for lint in ["clippy::all", "clippy::pedantic", "missing_docs"] {
            assert!(GENERATED_ALLOWS.contains(lint));
        }
    }
}
